"""Real rows from the live corpus, projected through `access_levels` at the
moment they were captured, so a reader sees actual values rather than a shape
full of nulls. The league and the Member API block are constructed — there is no
league to capture yet, and a live event mid-round is not a row anyone holds."""

import json

TOURNAMENT = {
    "uid": "019fea18-1364-7549-8f9a-70dcc09a03d9",
    "name": "V:TES Tournament: Malmö Unbound",
    "rank": "",
    "start": "2026-06-13T10:00:00",
    "state": "Finished",
    "timer": {"paused": True, "started_at": None, "elapsed_before_pause": 0.0},
    "venue": 'Spelens hus "malmö"',
    "finals": {
        "state": "Finished",
        "seating": [
            {
                "result": {"gw": 1, "tp": 0, "vp": 1.5},
                "judge_uid": "",
                "player_uid": "019f6a5e-dc94-77b5-814d-20920477f87d",
            },
            {
                "result": {"gw": 0, "tp": 0, "vp": 0.5},
                "judge_uid": "",
                "player_uid": "019f6a5e-d5dd-74b9-9aab-00919d4de7dc",
            },
            {
                "result": {"gw": 0, "tp": 0, "vp": 0.5},
                "judge_uid": "",
                "player_uid": "019f6a5e-b052-7550-8422-1cc8e42309b2",
            },
            {
                "result": {"gw": 0, "tp": 0, "vp": 0.0},
                "judge_uid": "",
                "player_uid": "019f6a5e-f546-7049-8f16-2d81aa97eac3",
            },
            {
                "result": {"gw": 0, "tp": 0, "vp": 0.5},
                "judge_uid": "",
                "player_uid": "019f6a5e-e0e8-7702-a583-c1a6f6a005fe",
            },
        ],
        "override": None,
        "seed_order": [
            "019f6a5e-dc94-77b5-814d-20920477f87d",
            "019f6a5e-d5dd-74b9-9aab-00919d4de7dc",
            "019f6a5e-b052-7550-8422-1cc8e42309b2",
            "019f6a5e-f546-7049-8f16-2d81aa97eac3",
            "019f6a5e-e0e8-7702-a583-c1a6f6a005fe",
        ],
        "organized_by": None,
    },
    "finish": "2026-06-13T10:00:00",
    "format": "Standard",
    "online": False,
    "rounds": [],
    "winner": "019f6a5e-dc94-77b5-814d-20920477f87d",
    "address": "Nobelvägen 145A, Malmö",
    "country": "SE",
    "map_url": "https://www.google.com/maps/search/?api=1&query=Spelens%20hus%20%22malm%C3%B6%22%20Nobelv%C3%A4gen%20145A%2C%20Malm%C3%B6%20SE",
    "players": [
        {
            "toss": 0,
            "state": "Finished",
            "result": {"gw": 2, "tp": 114, "vp": 6.5},
            "finalist": True,
            "user_uid": "019f6a5e-dc94-77b5-814d-20920477f87d",
            "non_competing": False,
        },
        {
            "toss": 0,
            "state": "Finished",
            "result": {"gw": 1, "tp": 162, "vp": 5.5},
            "finalist": True,
            "user_uid": "019f6a5e-d5dd-74b9-9aab-00919d4de7dc",
            "non_competing": False,
        },
        {
            "toss": 0,
            "state": "Finished",
            "result": {"gw": 2, "tp": 174, "vp": 9.0},
            "finalist": True,
            "user_uid": "019f6a5e-b052-7550-8422-1cc8e42309b2",
            "non_competing": False,
        },
        {
            "toss": 0,
            "state": "Finished",
            "result": {"gw": 1, "tp": 120, "vp": 3.0},
            "finalist": True,
            "user_uid": "019f6a5e-f546-7049-8f16-2d81aa97eac3",
            "non_competing": False,
        },
        {
            "toss": 0,
            "state": "Finished",
            "result": {"gw": 2, "tp": 168, "vp": 5.5},
            "finalist": True,
            "user_uid": "019f6a5e-e0e8-7702-a583-c1a6f6a005fe",
            "non_competing": False,
        },
        {
            "toss": 0,
            "state": "Finished",
            "result": {"gw": 1, "tp": 96, "vp": 3.0},
            "finalist": False,
            "user_uid": "019f6a5e-ac10-77da-9d8a-f76167d04c02",
            "non_competing": False,
        },
        {
            "toss": 0,
            "state": "Finished",
            "result": {"gw": 0, "tp": 94, "vp": 1.5},
            "finalist": False,
            "user_uid": "019f6a5e-f545-7053-8d3c-7fb36549641b",
            "non_competing": False,
        },
        {
            "toss": 0,
            "state": "Finished",
            "result": {"gw": 0, "tp": 90, "vp": 1.0},
            "finalist": False,
            "user_uid": "019f6a5e-ae0e-71a3-bcf5-43e58752e226",
            "non_competing": False,
        },
        {
            "toss": 0,
            "state": "Finished",
            "result": {"gw": 0, "tp": 88, "vp": 1.0},
            "finalist": False,
            "user_uid": "019f6a5e-e0ef-76e6-b438-03b5a51c7d12",
            "non_competing": False,
        },
        {
            "toss": 0,
            "state": "Finished",
            "result": {"gw": 0, "tp": 84, "vp": 1.0},
            "finalist": False,
            "user_uid": "019f6a5e-ece2-73b0-9dac-6c99d5a70141",
            "non_competing": False,
        },
        {
            "toss": 0,
            "state": "Finished",
            "result": {"gw": 0, "tp": 82, "vp": 1.0},
            "finalist": False,
            "user_uid": "019f6a5e-a893-77c8-9ada-3c8ace2e00ff",
            "non_competing": False,
        },
        {
            "toss": 0,
            "state": "Finished",
            "result": {"gw": 0, "tp": 72, "vp": 1.0},
            "finalist": False,
            "user_uid": "019f6a5e-ecde-7456-8f15-720512422db3",
            "non_competing": False,
        },
        {
            "toss": 0,
            "state": "Finished",
            "result": {"gw": 0, "tp": 60, "vp": 0.0},
            "finalist": False,
            "user_uid": "019f6a5e-fcdc-74ae-9217-3c68cf3831dc",
            "non_competing": False,
        },
    ],
    "proxies": True,
    "timezone": "Europe/Stockholm",
    "multideck": False,
    "standings": [
        {
            "gw": 2.0,
            "tp": 174,
            "vp": 8.5,
            "toss": 0,
            "finalist": True,
            "user_uid": "019f6a5e-b052-7550-8422-1cc8e42309b2",
            "disqualified": False,
            "non_competing": False,
        },
        {
            "gw": 2.0,
            "tp": 168,
            "vp": 5.0,
            "toss": 0,
            "finalist": True,
            "user_uid": "019f6a5e-e0e8-7702-a583-c1a6f6a005fe",
            "disqualified": False,
            "non_competing": False,
        },
        {
            "gw": 1.0,
            "tp": 162,
            "vp": 5.0,
            "toss": 0,
            "finalist": True,
            "user_uid": "019f6a5e-d5dd-74b9-9aab-00919d4de7dc",
            "disqualified": False,
            "non_competing": False,
        },
        {
            "gw": 1.0,
            "tp": 114,
            "vp": 5.0,
            "toss": 0,
            "finalist": True,
            "user_uid": "019f6a5e-dc94-77b5-814d-20920477f87d",
            "disqualified": False,
            "non_competing": False,
        },
        {
            "gw": 1.0,
            "tp": 120,
            "vp": 3.0,
            "toss": 0,
            "finalist": True,
            "user_uid": "019f6a5e-f546-7049-8f16-2d81aa97eac3",
            "disqualified": False,
            "non_competing": False,
        },
        {
            "gw": 1.0,
            "tp": 96,
            "vp": 3.0,
            "toss": 0,
            "finalist": False,
            "user_uid": "019f6a5e-ac10-77da-9d8a-f76167d04c02",
            "disqualified": False,
            "non_competing": False,
        },
        {
            "gw": 0.0,
            "tp": 94,
            "vp": 1.5,
            "toss": 0,
            "finalist": False,
            "user_uid": "019f6a5e-f545-7053-8d3c-7fb36549641b",
            "disqualified": False,
            "non_competing": False,
        },
        {
            "gw": 0.0,
            "tp": 90,
            "vp": 1.0,
            "toss": 0,
            "finalist": False,
            "user_uid": "019f6a5e-ae0e-71a3-bcf5-43e58752e226",
            "disqualified": False,
            "non_competing": False,
        },
        {
            "gw": 0.0,
            "tp": 88,
            "vp": 1.0,
            "toss": 0,
            "finalist": False,
            "user_uid": "019f6a5e-e0ef-76e6-b438-03b5a51c7d12",
            "disqualified": False,
            "non_competing": False,
        },
        {
            "gw": 0.0,
            "tp": 84,
            "vp": 1.0,
            "toss": 0,
            "finalist": False,
            "user_uid": "019f6a5e-ece2-73b0-9dac-6c99d5a70141",
            "disqualified": False,
            "non_competing": False,
        },
        {
            "gw": 0.0,
            "tp": 82,
            "vp": 1.0,
            "toss": 0,
            "finalist": False,
            "user_uid": "019f6a5e-a893-77c8-9ada-3c8ace2e00ff",
            "disqualified": False,
            "non_competing": False,
        },
        {
            "gw": 0.0,
            "tp": 72,
            "vp": 1.0,
            "toss": 0,
            "finalist": False,
            "user_uid": "019f6a5e-ecde-7456-8f15-720512422db3",
            "disqualified": False,
            "non_competing": False,
        },
        {
            "gw": 0.0,
            "tp": 60,
            "vp": 0.0,
            "toss": 0,
            "finalist": False,
            "user_uid": "019f6a5e-fcdc-74ae-9217-3c68cf3831dc",
            "disqualified": False,
            "non_competing": False,
        },
    ],
    "venue_url": "",
    "league_uid": None,
    "max_rounds": 3,
    "round_time": 0,
    "banner_path": None,
    "description": "",
    "finals_time": 0,
    "max_players": 0,
    "open_rounds": False,
    "table_rooms": [],
    "external_ids": {"vekn": "13370"},
    "offline_mode": False,
    "offline_since": None,
    "decklists_mode": "Winner",
    "standings_mode": "Private",
    "organizers_uids": ["019f6a5e-d5dd-74b9-9aab-00919d4de7dc"],
    "offline_user_uid": "",
    "table_extra_time": {},
    "decklist_required": False,
    "self_organized_rounds": False,
}

USER = {
    "uid": "019f6a5e-d1e6-7347-965e-4dac09bf03a4",
    "wins": ["019f6a63-beed-75ec-aa68-721e0fb88b36"],
    "roles": ["Rulemonger", "IC", "Prince"],
    "country": "FR",
    "vekn_id": "3200340",
    "limited_online": None,
    "community_links": [
        {
            "url": "https://codex-of-the-damned.org",
            "type": "website",
            "label": "Codex of the Damned",
            "country": "FR",
            "languages": ["fr", "en", "es", "pt"],
            "moderation": None,
        },
        {
            "url": "https://discord.gg/vampire-the-eternal-struggle-official-887471681277399091",
            "type": "discord",
            "label": "VTES Discord",
            "country": "GB",
            "languages": [],
            "moderation": "global",
        },
        {
            "url": "https://www.vekn.fr/forum/",
            "type": "forum",
            "label": "VEKN France",
            "country": "FR",
            "languages": [],
            "moderation": "national",
        },
    ],
    "limited_offline": None,
    "constructed_online": {
        "total": 5,
        "tournaments": [
            {
                "gw": 0,
                "vp": 0.0,
                "date": "2026-07-12",
                "rank": "",
                "points": 5,
                "position": 13,
                "player_count": 18,
                "tournament_uid": "019f6a64-e879-719f-bf45-7410de773df3",
                "tournament_name": "Third Road to Vilnius 2026",
                "finalist_position": 0,
            }
        ],
    },
    "constructed_offline": {"total": 0, "tournaments": []},
}

DECK = {
    "uid": "019f6a65-01d4-7214-bcc9-4e46534b9d62",
    "name": "",
    "cards": {
        "100064": 1,
        "100065": 1,
        "100074": 2,
        "100085": 1,
        "100095": 1,
        "100119": 2,
        "100493": 1,
        "100588": 3,
        "100652": 2,
        "100737": 2,
        "100824": 1,
        "100842": 2,
        "100903": 1,
        "100909": 1,
        "101028": 2,
        "101056": 7,
        "101144": 5,
        "101145": 1,
        "101271": 2,
        "101321": 2,
        "101353": 7,
        "101500": 1,
        "101591": 1,
        "101681": 1,
        "101686": 4,
        "101711": 1,
        "101896": 1,
        "101949": 4,
        "101955": 1,
        "101989": 8,
        "102121": 6,
        "102131": 7,
        "102207": 8,
        "200049": 3,
        "200106": 3,
        "200107": 3,
        "200330": 2,
        "200345": 1,
    },
    "round": None,
    "comments": "",
    "user_uid": "019f6a5e-c78e-733e-bf17-d246b2b4c7ef",
    "attribution": "twda",
    "tournament_uid": "019f6a5f-b16b-7673-9218-a9b9b92ca380",
}

COMMUNITY_LINK_ENTRY = {
    "vekn_id": "3200340",
    "link": {
        "url": "https://codex-of-the-damned.org",
        "type": "website",
        "label": "Codex of the Damned",
        "country": "FR",
        "languages": ["fr", "en", "es", "pt"],
        "moderation": None,
    },
}

LEAGUE = {
    "uid": "019fe07a-b107-7465-9968-122ceb6d67d1",
    "name": "Nordic Chapter 2026",
    "kind": "League",
    "format": "Standard",
    "country": "SE",
    "description": "Every sanctioned Standard event held in the Nordics in 2026.",
    "start": "2026-01-01T00:00:00",
    "finish": "2026-12-31T23:59:59",
    "standings_mode": "GP",
    "organizers_uids": ["019f6a5e-d5dd-74b9-9aab-00919d4de7dc"],
    "parent_uid": None,
    "open_to_country_princes": True,
}


# Member API: the app's own documents, not the projection above.
# `test_public_api.py` decodes them back into their models, so a model change that
# outdates one fails there.

MEMBER_TOURNAMENT = {
    "uid": "019ff0c2-51e8-7a6d-b58c-4e9a2f7d1c03",
    "modified": "2026-05-02T14:31:07.481Z",
    "deleted_at": None,
    "name": "Rome Monthly",
    "format": "Standard",
    "rank": "",
    "online": False,
    "start": "2026-05-02T10:00:00",
    "finish": None,
    "timezone": "Europe/Rome",
    "country": "IT",
    "league_uid": None,
    "state": "Playing",
    "organizers_uids": ["019f6a5e-a1b7-7c40-b0e2-63dd51ba7a10"],
    "venue": "Ludoteca Trastevere",
    "venue_url": "",
    "address": "Via della Lungaretta 12, Roma",
    "map_url": "",
    "proxies": False,
    "multideck": False,
    "decklist_required": False,
    "description": "",
    "standings_mode": "Private",
    "decklists_mode": "Winner",
    "max_rounds": 3,
    "max_players": 0,
    "open_rounds": False,
    "self_organized_rounds": False,
    "table_rooms": [],
    "round_time": 120,
    "finals_time": 150,
    "banner_path": None,
    "external_ids": {},
    "event_code": "RM-2605",
    "checkin_code": "Qk9tYVJvbWFNb250aGx5",
    "players": [
        {
            "user_uid": "019f6a5e-dc94-77b5-814d-20920477f87d",
            "state": "Playing",
            "payment_status": "Pending",
            "toss": 0,
            "result": {"gw": 1, "vp": 3.0, "tp": 42},
            "finalist": False,
            "display_name": None,
            "non_competing": False,
            "missing_decklist": False,
            "waitlisted": False,
        },
        {
            "user_uid": "019f6a5e-d5dd-74b9-9aab-00919d4de7dc",
            "state": "Playing",
            "payment_status": "Pending",
            "toss": 0,
            "result": {"gw": 0, "vp": 1.0, "tp": 30},
            "finalist": False,
            "display_name": None,
            "non_competing": False,
            "missing_decklist": False,
            "waitlisted": False,
        },
        {
            "user_uid": "019f6a5e-b052-7550-8422-1cc8e42309b2",
            "state": "Playing",
            "payment_status": "Pending",
            "toss": 0,
            "result": {"gw": 0, "vp": 1.0, "tp": 24},
            "finalist": False,
            "display_name": None,
            "non_competing": False,
            "missing_decklist": False,
            "waitlisted": False,
        },
        {
            "user_uid": "019f6a5e-f546-7049-8f16-2d81aa97eac3",
            "state": "Playing",
            "payment_status": "Pending",
            "toss": 0,
            "result": {"gw": 0, "vp": 0.0, "tp": 12},
            "finalist": False,
            "display_name": None,
            "non_competing": False,
            "missing_decklist": False,
            "waitlisted": False,
        },
        {
            "user_uid": "019f6a5e-e0e8-7702-a583-c1a6f6a005fe",
            "state": "Playing",
            "payment_status": "Pending",
            "toss": 0,
            "result": {"gw": 0, "vp": 0.0, "tp": 0},
            "finalist": False,
            "display_name": None,
            "non_competing": False,
            "missing_decklist": False,
            "waitlisted": False,
        },
    ],
    "rounds": [
        [
            {
                "seating": [
                    {
                        "player_uid": "019f6a5e-dc94-77b5-814d-20920477f87d",
                        "result": {"gw": 1, "vp": 3.0, "tp": 42},
                        "judge_uid": "",
                    },
                    {
                        "player_uid": "019f6a5e-d5dd-74b9-9aab-00919d4de7dc",
                        "result": {"gw": 0, "vp": 1.0, "tp": 30},
                        "judge_uid": "",
                    },
                    {
                        "player_uid": "019f6a5e-b052-7550-8422-1cc8e42309b2",
                        "result": {"gw": 0, "vp": 1.0, "tp": 24},
                        "judge_uid": "",
                    },
                    {
                        "player_uid": "019f6a5e-f546-7049-8f16-2d81aa97eac3",
                        "result": {"gw": 0, "vp": 0.0, "tp": 12},
                        "judge_uid": "",
                    },
                    {
                        "player_uid": "019f6a5e-e0e8-7702-a583-c1a6f6a005fe",
                        "result": {"gw": 0, "vp": 0.0, "tp": 0},
                        "judge_uid": "",
                    },
                ],
                "state": "Finished",
                "override": None,
                "organized_by": None,
            }
        ]
    ],
    "finals": None,
    "winner": "",
    "standings": [],
    "reported_player_count": 0,
    "raffles": [],
    "promos_distributed": [],
    "promo_stock_source_uid": "",
    "vekn_pushed_at": None,
    "vekn_results_stale": False,
    "vekn_event_absent_at": None,
    "twda_status": None,
    "offline_mode": False,
    "offline_device_id": "",
    "offline_user_uid": "",
    "offline_since": None,
    "timer": {
        "started_at": "2026-05-02T14:20:00Z",
        "elapsed_before_pause": 0.0,
        "paused": False,
    },
    "table_extra_time": {},
    "announcements": [
        {
            "id": "019ff0c3-0a11-7e42-9d6b-8f2c4a1b73ee",
            "body": "Round 2 seating is up — tables in the back room.",
            "created_at": "2026-05-02T14:31:00Z",
            "author_uid": "019f6a5e-a1b7-7c40-b0e2-63dd51ba7a10",
            "author_name": "Marco Rossi",
        }
    ],
}

ROUND_DECKS = {
    "rounds": [
        {
            "round": 0,
            "decks": [
                {
                    "uid": "019ff0c4-77aa-7b19-9e30-5c1d8e6f2a44",
                    "modified": "2026-05-02T13:58:12.006Z",
                    "deleted_at": None,
                    "tournament_uid": "019ff0c2-51e8-7a6d-b58c-4e9a2f7d1c03",
                    "user_uid": "019f6a5e-dc94-77b5-814d-20920477f87d",
                    "round": 0,
                    "name": "Nephandus Toolbox",
                    "author": "Giulia Bianchi",
                    "comments": "",
                    "cards": {"100001": 4, "100638": 2, "101453": 10, "102079": 12},
                    "attribution": None,
                    "public": False,
                }
            ],
        }
    ]
}

SANCTION = {
    "uid": "019ff0c5-1d3e-7f08-8a72-11b9c0d4e6f7",
    "modified": "2026-05-02T14:22:03.114Z",
    "deleted_at": None,
    "user_uid": "019f6a5e-f546-7049-8f16-2d81aa97eac3",
    "issued_by_uid": "019f6a5e-a1b7-7c40-b0e2-63dd51ba7a10",
    "tournament_uid": "019ff0c2-51e8-7a6d-b58c-4e9a2f7d1c03",
    "level": "warning",
    "category": "tournament_error",
    "subcategory": "slow_play",
    "round_number": 0,
    "description": "Repeated slow play after a first caution.",
    "issued_at": "2026-05-02T14:22:03.114Z",
    "expires_at": None,
    "lifted_at": None,
    "lifted_by_uid": None,
}

STREAM_SANCTION = {
    "uid": "019ff0c5-1d3e-7f08-8a72-11b9c0d4e6f7",
    "modified": "2026-05-02T14:22:03.114Z",
    "deleted_at": None,
    "user_uid": "019f6a5e-f546-7049-8f16-2d81aa97eac3",
    "issued_by_uid": "019f6a5e-a1b7-7c40-b0e2-63dd51ba7a10",
    "tournament_uid": "019ff0c2-51e8-7a6d-b58c-4e9a2f7d1c03",
    "level": "warning",
    "category": "tournament_error",
    "subcategory": "slow_play",
    "round_number": 0,
    "description": "Repeated slow play after a first caution.",
    "issued_at": "2026-05-02T14:22:03.114Z",
    "expires_at": None,
    "lifted_at": None,
    "lifted_by_uid": None,
}

STREAM_PARTICIPANT = {
    "uid": "019f6a5e-dc94-77b5-814d-20920477f87d",
    "modified": "2026-04-11T09:02:44.318Z",
    "deleted_at": None,
    "name": "Giulia Bianchi",
    "country": "IT",
    "vekn_id": "1002346",
    "city": None,
    "city_geoname_id": None,
    "state": None,
    "nickname": None,
    "roles": [],
    "avatar_path": None,
    "discord_id": None,
    "deceased_at": None,
    "vekn_prefix": None,
    "constructed_online": None,
    "constructed_offline": None,
    "limited_online": None,
    "limited_offline": None,
    "wins": [],
}

USERINFO = {
    "sub": "019f6a5e-a1b7-7c40-b0e2-63dd51ba7a10",
    "roles": ["Prince", "Judge"],
    "vekn_id": "1002345",
    "capabilities": ["sponsor_member", "create_tournament"],
}

SANCTION_REFERENCE = {
    "categories": [
        {
            "key": "procedural_error",
            "label": "Procedural Error",
            "subcategories": [
                {
                    "key": "missed_mandatory_effect",
                    "label": "Missed Mandatory Effect",
                    "baseline": "caution",
                },
                {
                    "key": "card_access_error",
                    "label": "Card Access Error",
                    "baseline": "caution",
                },
                {
                    "key": "game_rule_violation",
                    "label": "Game Rule Violation",
                    "baseline": "caution",
                },
                {
                    "key": "failure_to_maintain_game_state",
                    "label": "Failure to Maintain Game State",
                    "baseline": "standings_adjustment",
                },
            ],
        },
        {
            "key": "tournament_error",
            "label": "Tournament Error",
            "subcategories": [
                {
                    "key": "illegal_decklist",
                    "label": "Illegal Decklist",
                    "baseline": "warning",
                },
                {
                    "key": "illegal_main_deck_legal_decklist",
                    "label": "Illegal Main Deck (Legal Decklist)",
                    "baseline": "standings_adjustment",
                },
                {
                    "key": "illegal_main_deck_no_decklist",
                    "label": "Illegal Main Deck (No Decklist)",
                    "baseline": "standings_adjustment",
                },
                {
                    "key": "outside_assistance",
                    "label": "Outside Assistance",
                    "baseline": "standings_adjustment",
                },
                {"key": "slow_play", "label": "Slow Play", "baseline": "caution"},
                {
                    "key": "limited_procedure_violation",
                    "label": "Limited Procedure Violation",
                    "baseline": "caution",
                },
                {
                    "key": "public_info_miscommunication",
                    "label": "Public Info Miscommunication",
                    "baseline": "warning",
                },
                {
                    "key": "obscuring_game_state",
                    "label": "Obscuring Game State",
                    "baseline": "caution",
                },
                {"key": "marked_cards", "label": "Marked Cards", "baseline": "warning"},
                {
                    "key": "insufficient_shuffling",
                    "label": "Insufficient Shuffling",
                    "baseline": "warning",
                },
            ],
        },
        {
            "key": "unsportsmanlike_conduct",
            "label": "Unsportsmanlike Conduct",
            "subcategories": [
                {"key": "minor", "label": "Minor", "baseline": "warning"},
                {"key": "major", "label": "Major", "baseline": "standings_adjustment"},
                {
                    "key": "aggressive_behaviour",
                    "label": "Aggressive Behaviour",
                    "baseline": "disqualification",
                },
                {
                    "key": "bribery_and_wagering",
                    "label": "Bribery and Wagering",
                    "baseline": "disqualification",
                },
                {
                    "key": "theft_of_tournament_material",
                    "label": "Theft of Tournament Material",
                    "baseline": "disqualification",
                },
                {
                    "key": "stalling",
                    "label": "Stalling",
                    "baseline": "disqualification",
                },
                {
                    "key": "cheating",
                    "label": "Cheating",
                    "baseline": "disqualification",
                },
                {"key": "fraud", "label": "Fraud", "baseline": "disqualification"},
                {
                    "key": "collusion",
                    "label": "Collusion",
                    "baseline": "disqualification",
                },
                {
                    "key": "health_and_safety_disruption",
                    "label": "Health and Safety Disruption",
                    "baseline": "warning",
                },
                {
                    "key": "rage_quitting",
                    "label": "Rage Quitting",
                    "baseline": "disqualification",
                },
                {
                    "key": "failure_to_play_to_win",
                    "label": "Failure to Play to Win",
                    "baseline": "warning",
                },
            ],
        },
    ],
    "levels": [
        {"key": "caution", "label": "Caution"},
        {"key": "warning", "label": "Warning"},
        {"key": "standings_adjustment", "label": "Standings Adjustment"},
        {"key": "disqualification", "label": "Disqualification"},
    ],
    "escalation": [
        "caution",
        "caution",
        "warning",
        "warning",
        "standings_adjustment",
        "standings_adjustment",
        "disqualification",
    ],
}


def _frame(obj_type: str, payload, **extra) -> str:
    body = json.dumps(payload, separators=(",", ":"))
    tail = "".join(f',"{k}":"{v}"' for k, v in extra.items())
    return f'data: {{"type":"{obj_type}","data":{body}{tail}}}\n\n'


# Catch-up in full, then the frames a running event pushes. `ts` rides the live
# ones only: it is the cursor a reconnecting client would resume from.
STREAM = (
    ": connected\n\n"
    + _frame("tournament", MEMBER_TOURNAMENT)
    + _frame("sanctions", [STREAM_SANCTION])
    + _frame("user", STREAM_PARTICIPANT)
    + 'data: {"type":"sync_complete","timestamp":"2026-05-02T14:31:07.481Z"}\n\n'
    + _frame("tournament", MEMBER_TOURNAMENT, ts="2026-05-02T14:33:19.702Z")
)
