"""Type stubs for the archon_engine Rust/PyO3 module."""

class PyEngine:
    def __init__(self) -> None: ...
    def can_change_role(self, actor_json: str, target_json: str, role: str) -> str: ...
    def can_manage_vekn(self, actor_json: str, target_json: str) -> str: ...
    def can_edit_user(
        self, actor_json: str, actor_uid: str, target_uid: str, target_json: str
    ) -> str: ...
    def compute_seating(self, config_json: str) -> str: ...
    def score_seating(self, config_json: str) -> str: ...
    def process_tournament_event(
        self,
        tournament_json: str,
        event_json: str,
        actor_json: str,
        sanctions_json: str,
        decks_json: str,
    ) -> str: ...
    def compute_rating_points(
        self, vp: float, gw: int, finalist_position: int, player_count: int, rank: str
    ) -> int: ...
    def rating_category(self, format: str, online: bool) -> str: ...
    def parse_deck(self, text: str, cards_json: str) -> str: ...
    def validate_deck(self, deck_json: str, cards_json: str, format: str) -> str: ...
    def enrich_deck(self, deck_json: str, cards_json: str) -> str: ...
    def compute_league_standings(self, config_json: str) -> str: ...
    def compute_player_issues(self, config_json: str) -> str: ...
    def export_twda(
        self,
        deck_json: str,
        cards_json: str,
        tournament_name: str,
        tournament_date: str,
        tournament_place: str,
        tournament_format: str,
        tournament_url: str,
        player_count: int,
        player_name: str,
    ) -> str: ...
    def check_table_vps(self, vps: list[float]) -> str | None: ...
    def compute_gw(self, vps: list[float], adjustments: list[float]) -> list[float]: ...
    def compute_tp(self, table_size: int, vps: list[float]) -> list[float]: ...
