---
- name: Allow OpenSSH
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow HTTPS
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp

- name: Enable ufw with default deny
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
