---
- name: Reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: Restart unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted
