#ENC[AES256_GCM,data:69SQ/qugozzX+0MXA0qiKUFFKcyIF1TSlp1EVPwpcRg6lSkeEXQcuTC3NiZg4FydIuSVgieqE9SQawUkeUYKn3WOYjOK821Oeam1oz8=,iv:NEQcLKoSfagIXsbkqg3uZbJLbvT2vUc02DFZKRgmAhw=,tag:mLpNC7lqPumOT/c06qgnBQ==,type:comment]
#ENC[AES256_GCM,data:QUkiO73vVe+gND4Otjy4wqn4J64r3NkM7s+f3kA/6CTJ7EHa+TDLO2GtNXRJEe3prAqZ+IITaCVyVSaa7QLJosrWMS+BNAtxb3eJUReNPg==,iv:h4xrNU99keamEla4IyZSHG4drAHT+h94M+BBTRC82wY=,tag:WYxFZsIxd8qrJ8iGPy4SCw==,type:comment]
#ENC[AES256_GCM,data:r6Cd9AqENsZOfiWE0XpYgsZRyPEAmI0Ie6OiTeoo8kGgWUV6G5NrZgQKhu69,iv:g3PO/ErAamx5peMmOLUJ4D0QsmDKQA+WXNBoazDW63A=,tag:1lfxPp8XZaUNVLZ5OXWBqA==,type:comment]
#ENC[AES256_GCM,data:dGgHAHDfGLRlZIglJPbu28EtpXTYGl7/KcuTToHlLB9VG3kHNW5N+i3tWR0O6E79D+H7ImOTLjmUnkSzAATFPTXWEayG5stHcSrrcWg=,iv:6tqyVqwIh7SZj5G5NBHuW44h0MfjiPAPVTXK4y9Icr8=,tag:rknbMJlZ8S4xWwrxWAILOQ==,type:comment]
db_password: ENC[AES256_GCM,data:/VaDnUFnD5/aRlK4KZZ8cgeDPLmpcATdw+erqjj2eX4IX7Z9gI6afuqlnnmFNi+a,iv:WQ8BqxZXVHmnbrTTDEEXs2Any+84u+/OLr5k65/lLFg=,tag:HWrltOxM0sLgftrMRLBlsg==,type:str]
jwt_secret: ENC[AES256_GCM,data:0DRfYW/cWta+KHszd+/nFCoEKZBt+/sRuKQ8M/xqOjL7ZTZ1KUC9JsHs7Icr6n2ZFXoeZxnfPtkyi0aw60UQEQ==,iv:aDuOARlmWkrazmBTodWFnGwpeqUpPz4qO9a7CfP1fUI=,tag:Gmb5xCGrvPDSM1iKRxFsIA==,type:str]
mail_password: ENC[AES256_GCM,data:b4yxMUJKkYMscZVxpLuwtlybDQ==,iv:AuTkA6W33bM+A3+QqrDAVGPgBeYyZQgQDZao5xVHLDI=,tag:YfPycgwH6RQmKk0GWNS+iw==,type:str]
discord_client_id: "1465095871485186231"
discord_client_secret: ENC[AES256_GCM,data:DKPsZOJf39+XQSBdGIyHjpdQto/WgB0U5T2NP5EdK/Y=,iv:rt8pXwAx0PIioXXhOdDVQRqW/iK8FwwzIbJR8eu5J0E=,tag:IanPKQ6QN+g8x2WqqKKNiA==,type:str]
discord_bot_token: ENC[AES256_GCM,data:S3f9QtXOr1otWhsCzVgv7xFwmQTyGEiYGxkNytxxW33S2ZJSFUwbnLxK1Din5YMtig2FiN1kenRQWwIlk4jkUXwRNeZF4J3+,iv:r5zfEBiCKVgcAhfIu7mI1nSih9d4MvUHdWe8hyTdAVw=,tag:nFpfINnt4z9jVvyKI9RuBA==,type:str]
bot_oauth_client_id: SO0J4r5QoluF0yQs83N-lLF33A8EP8Cw
bot_oauth_client_secret: ENC[AES256_GCM,data:8BLMqcSVO2iYDTWbxRQ5Og62DY4BS6pqcPSWZyD7Mrq5QWdUIccZr5U2lIFQ2uGua7rTD9+peAy5nWoBecFI/A==,iv:hb2J3rl6x13grEhLVu/saNTrwANC2J6e29BAx3QF2z8=,tag:9Z2PKlTkqpAnSRtjORuYJg==,type:str]
vekn_username: lip
vekn_password: ENC[AES256_GCM,data:sxgzP8XREo28OY4w6K06,iv:vEQnYWJCjSMi4KCQuTAF1QI6q2H9zS1JaHc2kXH84CE=,tag:+xVPwtMDpnEfuBB38r781w==,type:str]
twda_github_client_id: Iv23liMqTbrMiNflWqLO
twda_github_installation_id: "143142734"
feedback_github_client_id: Iv23liCZ9rhxGfKpz2mi
feedback_github_installation_id: "142627061"
vapid_private_key: ENC[AES256_GCM,data:Y0n7cnzG7NnyRrWzDuc3nOusrPFiaSaeHPI+R6t3sHsyH8NqujLxhSrPxg==,iv:UXLRuyObFxnaNL7dvMjEH7ogX+Jv51xnu9hDFJADu8Q=,tag:0G2wB+q63NzXm1kP5CFHGg==,type:str]
vapid_public_key: BP-ptCQKVlaaYmffrS9ZOaYzpnsRIX5C0eHVPy8g6aaqLgEKsOiFQkCX18vsGjgVmWGH1Osek_5HiFJI91FenMo
github_oauth_client_id: Ov23liEiLJGegVfQU3cT
github_oauth_secret: ENC[AES256_GCM,data:uv6h6QBYdh1a38qgry2X0RrIynBfx+ccru+nfBSQEqqrDIMjnnssxA==,iv:mCnMz9OrdO4WDkkt5knBB02blmmzi7O555bV2WK9IYQ=,tag:n0Z8zFuDHNQ+hqtNIe8xkg==,type:str]
jwt_private_key: ENC[AES256_GCM,data:XNb2ZZvs0jWHczodCEeNRvutzxdcY1waO6mYtR4UQs5QUXRP4MXxhw/KqQ==,iv:xwzeQ8FTNYM2F57j9Pj06zXq60DV0T/rwXxXi2fKESs=,tag:4ppxAy7Ne1OvcFkgkA5J/Q==,type:str]
jwt_public_keys: hRwGlsnSw8Rcem5w0fulvEqhpTL26w9JzuFyNLMoFRU
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGdRTUZwQSBIYWxo
            U1RrL2JtNSs5OGZNOTgwZCs3bi8weVFOMGRnZ3NialhMK2lPaTFjCml6a0dGQi9M
            ZnJSNUZrVXY0TXRUaFlKTnRmaGdzUUtpTXI1L21ha2N0L1kKLS0tIEpidG1ZQllH
            dVd5MDZDRWFUZGwveEwzZ01wZnBxbkkzanJ1NUdMb0RBNVUKzWLUn7KY4FcIW4ve
            QQsSYGnAmwSN7GtRj3Zq/29S/y4gA4lAJRCTmtLcJ3PQSHD3WC8yb3rM3dp/H8OW
            Il6o8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE+Fa+dmnpPBYM0G7xPupl+GkVdF6YFmZ/NkpyqOzWoI
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHp1NGdxUSBsM1VD
            aGVodVRFWlhNMmZEQndMMm55eHpxT2c2bUdMYkJ4enVYNjJBNEVzCmpOT25PbWp0
            dGtIZkVRMXF0RnR0NnhWMUZ6SnR5bDBiMlYrazJOT0ZTL3cKLS0tIHUweXR5d1Y0
            eU5qcVpDVEtnZm8wUVpFTHZjZmtPNjJOZjRjZDUzOGR6cGsKiPfpprH7iw8CIqst
            OMvN2PH+dlLWvgmQCbD2db7qzkm/Es80yLRyDvfX/warrADERqE1AeyOZzkR3Fkn
            mki0vQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDlN9QsXPGklb1BhEyGYankvkqoKGFlls4O0UWKe/YKf
    lastmodified: "2026-09-24T20:00:10Z"
    mac: ENC[AES256_GCM,data:YBdJy6w6b7ghRRFl6f/u7cDUGgvu3ThtOYyOFKRRAYCUfuRHV346QZ5kwpROp5A0U0fElCx/YAHt9K88UgKMN9W+17hrsk8Xdn86AIoqD6u7ji3CCiQLuB8+hTfiwCDd5dKItTAD6Fn97PwZLScErCTN4FgRzswSRsMfoUUDbrI=,iv:TNqeC20dlxFq1klaGDDJd5E2Ub+oeKcdNiMAxs0+fys=,tag:twfbSDsCcegq6D5qM6kVyQ==,type:str]
    unencrypted_regex: _(client_id|installation_id|public_keys?|username)$
    version: 3.13.3
