#ENC[AES256_GCM,data:dGgHAHDfGLRlZIglJPbu28EtpXTYGl7/KcuTToHlLB9VG3kHNW5N+i3tWR0O6E79D+H7ImOTLjmUnkSzAATFPTXWEayG5stHcSrrcWg=,iv:6tqyVqwIh7SZj5G5NBHuW44h0MfjiPAPVTXK4y9Icr8=,tag:rknbMJlZ8S4xWwrxWAILOQ==,type:comment]
#ENC[AES256_GCM,data:QUkiO73vVe+gND4Otjy4wqn4J64r3NkM7s+f3kA/6CTJ7EHa+TDLO2GtNXRJEe3prAqZ+IITaCVyVSaa7QLJosrWMS+BNAtxb3eJUReNPg==,iv:h4xrNU99keamEla4IyZSHG4drAHT+h94M+BBTRC82wY=,tag:WYxFZsIxd8qrJ8iGPy4SCw==,type:comment]
#ENC[AES256_GCM,data:r6Cd9AqENsZOfiWE0XpYgsZRyPEAmI0Ie6OiTeoo8kGgWUV6G5NrZgQKhu69,iv:g3PO/ErAamx5peMmOLUJ4D0QsmDKQA+WXNBoazDW63A=,tag:1lfxPp8XZaUNVLZ5OXWBqA==,type:comment]
#ENC[AES256_GCM,data:dGgHAHDfGLRlZIglJPbu28EtpXTYGl7/KcuTToHlLB9VG3kHNW5N+i3tWR0O6E79D+H7ImOTLjmUnkSzAATFPTXWEayG5stHcSrrcWg=,iv:6tqyVqwIh7SZj5G5NBHuW44h0MfjiPAPVTXK4y9Icr8=,tag:rknbMJlZ8S4xWwrxWAILOQ==,type:comment]
mail_password: ENC[AES256_GCM,data:nFcNVmAgykAylJxUyWCGbunikw==,iv:onSCzQyecy1bmEBI4OWRbWIcYSz8O26kFrbmT1USUic=,tag:jVuiIC2LJPmZjR/1fZGn1A==,type:str]
discord_client_id: "1465095871485186231"
discord_client_secret: ENC[AES256_GCM,data:cldCE2PN7kck8oChJr5o5oIiY0CQHOY6Y/AtgCuAV1o=,iv:3peefIXQHnuprqLaEeBhfznqJ2nYe+tczBQW8fgcXBQ=,tag:MB5xqw4pATU1/rEtpu0c/Q==,type:str]
discord_bot_token: ENC[AES256_GCM,data:evtFTkUj5H1jclcfs5dZV99aZjBj4eHNzMP4+TO/CWHcxkCXwDIsVDaPLcAyvCxRwqcCRNXs3RREBdI+3veCVHEEozHn7Ak/,iv:sOYmD0Tc5SMCjCi4YIsN/7u6DB8ywMf0TxRL0nPrcWs=,tag:IOh7O7VrVlBp4UDieq8Rbg==,type:str]
bot_oauth_client_id: SO0J4r5QoluF0yQs83N-lLF33A8EP8Cw
bot_oauth_client_secret: ENC[AES256_GCM,data:NBBQBWyc3gvWJR+/zDEJAGYFU9+JgNaJTUFqI7r47Mz2UdHWDqidTaGfxts7BqvxKSgXlRWFcu1J148PKdoieA==,iv:g6t8YSobQEBw4ce+uGOHLuDlbUGrQx0LRWhueyWOg5w=,tag:drCDxwwM33E0IZUCvSAgVQ==,type:str]
vekn_username: lip
vekn_password: ENC[AES256_GCM,data:MC5lzMucb8JQJX06mVZ4EI/3xyg=,iv:el7BQ3whF1GbF0Vlz1Gu7udQFYx6hu6PkdfJtykmAPY=,tag:Ojijvsl+dZ6Hc2gvcJLkKQ==,type:str]
twda_github_client_id: Iv23liMqTbrMiNflWqLO
twda_github_installation_id: "143142734"
feedback_github_client_id: Iv23liCZ9rhxGfKpz2mi
feedback_github_installation_id: "142627061"
vapid_private_key: ENC[AES256_GCM,data:Y0n7cnzG7NnyRrWzDuc3nOusrPFiaSaeHPI+R6t3sHsyH8NqujLxhSrPxg==,iv:UXLRuyObFxnaNL7dvMjEH7ogX+Jv51xnu9hDFJADu8Q=,tag:0G2wB+q63NzXm1kP5CFHGg==,type:str]
vapid_public_key: BP-ptCQKVlaaYmffrS9ZOaYzpnsRIX5C0eHVPy8g6aaqLgEKsOiFQkCX18vsGjgVmWGH1Osek_5HiFJI91FenMo
github_oauth_client_id: Ov23liEiLJGegVfQU3cT
github_oauth_secret: ENC[AES256_GCM,data:coXoEYT5/mbw7AX76YuO6DhBshyAlPyfZ9y5lITlfZaeluINMbdwvw==,iv:D5CSZbbHcGxWL3h7uvKLfyJWX2OQz8PwmlTvma685rg=,tag:rF5dg33pH9iFR7doHQZHbA==,type:str]
jwt_private_key: ENC[AES256_GCM,data:vTysrDbuPo0ilOpz6MYVIh1irEFbUZ+ovGBFu4An4I94GghBugg6VPBP0A==,iv:DQP7/1crxhdtsFCpSQh3CSkhS9SLxq1o9TAS0cwrR5U=,tag:LB+wngkPcsdz8hlDIh1LWQ==,type:str]
jwt_public_keys: repV-qUZJy9yDA5J7nmCBKXkEfcoQ10joP2GIIKC-vo
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGdRTUZwQSBIYWxo
            U1RrL2JtNSs5OGZNOTgwZCs3bi8weVFOMGRnZ3NialhMK2lPaTFjCml6a0dGQi9M
            ZnJSNUZrVXY0TXRUaFlKTnRmaGdzUUtpTXI1L21ha2N0L1kKLS0tIEpidG1ZQllH
            dVd5MDZDRWFUZGwveEwzZ01wZnBxbkkzanJ1NUdMb0RBNVUKzWLUn7KY4FcIW4ve
            QQsSYGnAmwSN7GtRj3Zq/29S/y4gA4lAJRCTmtLcJ3PQSHD3WC8yb3rM3dp/H8OW
            Il6o8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE+Fa+dmnpPBYM0G7xPupl+GkVdF6YFmZ/NkpyqOzWoI
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHp1NGdxUSBsM1VD
            aGVodVRFWlhNMmZEQndMMm55eHpxT2c2bUdMYkJ4enVYNjJBNEVzCmpOT25PbWp0
            dGtIZkVRMXF0RnR0NnhWMUZ6SnR5bDBiMlYrazJOT0ZTL3cKLS0tIHUweXR5d1Y0
            eU5qcVpDVEtnZm8wUVpFTHZjZmtPNjJOZjRjZDUzOGR6cGsKiPfpprH7iw8CIqst
            OMvN2PH+dlLWvgmQCbD2db7qzkm/Es80yLRyDvfX/warrADERqE1AeyOZzkR3Fkn
            mki0vQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDlN9QsXPGklb1BhEyGYankvkqoKGFlls4O0UWKe/YKf
    lastmodified: "2026-09-25T05:51:51Z"
    mac: ENC[AES256_GCM,data:BfUq3io3NZU3MuxqUHExzfqXBYCdFGBRdfTABMZQRRWv2o9WAmaSp8iUE12iAi8CPWU+7dNN+zi7xGAEy+QzFrt2inG557g0SZ+2kJ35ertATCrtMhNngYYBJEJGFiSyz7ICIkJ+fLnndVn/6q3JzWR61/KHYvd2kv1lSW/VjWg=,iv:biLV2jEmTJeyQwNRiNB/onQYGRrdDtdxOPsFXc4NFz4=,tag:YXCZQS0jxVTlSA9RriVDiA==,type:str]
    unencrypted_regex: _(client_id|installation_id|public_keys?|username)$
    version: 3.13.3
