#ENC[AES256_GCM,data:rBmX5xbkgtu7hHxPG1/Akk7cyR8SZXh2614blm3ft5GZMMDfwolP8Taiy3LQRLCXNkhtKe2lPKuY8WzZ4xDodnOz0a/J1OG4eTB8CAU=,iv:zEWhtDpZREM7XU28RX8pYF/Xs9hjH/oxgewFlIG1b+Y=,tag:kz7LYb4ofupq74e6/XhEIA==,type:comment]
#ENC[AES256_GCM,data:44EsyQJS2oS02sQXGV2Nber5c2NqbyBBOgoedpOGSS5beLG5QPwQSycSrrv68FoBw1IAWlBpHBLck1dMXdsmbpoovpbajkmrxLjAgqmDzYo5yyWPlw==,iv:crhqHIZx9O3zq1AGzGnpDCXn9P0Bp3rN7HOWom0/d6Y=,tag:BTvNQ5kOBB6UOhbSByDmXw==,type:comment]
#ENC[AES256_GCM,data:rBmX5xbkgtu7hHxPG1/Akk7cyR8SZXh2614blm3ft5GZMMDfwolP8Taiy3LQRLCXNkhtKe2lPKuY8WzZ4xDodnOz0a/J1OG4eTB8CAU=,iv:zEWhtDpZREM7XU28RX8pYF/Xs9hjH/oxgewFlIG1b+Y=,tag:kz7LYb4ofupq74e6/XhEIA==,type:comment]
mail_password: ENC[AES256_GCM,data:ZbcsNDIEsqAZ3QOzP7M7PKpBYg==,iv:6xEhiBeeA0m38xDmUhl6kwwFcsuGFGXOfJOxgtG582Q=,tag:uZ+rfNL67w7brC7nw0f+vw==,type:str]
discord_client_id: "1495034668469194864"
discord_client_secret: ENC[AES256_GCM,data:OAThNyqjSc/gr4ibRNU3aGjwuNv0XPfmvi//0vKocfs=,iv:yMvEFq37T/T5Cna7J5aeBAu/6WGQKVBbdqxMb9btPJQ=,tag:8DMCVWrBOwNQP/NXyjVZ6g==,type:str]
discord_bot_token: ENC[AES256_GCM,data:iZuk4RBUnGeU4SqMEAdp2uyvdkK117zT4FAycr0vLDzM+S4jqoCfTtKT81qGNWF4E8DKWTzHZg3jlW0zrEPY+lx69AFsF2pL,iv:OVv7EKAovu2HZ51HLY1b0/cXhGLX5ri7KDTQ86y13KQ=,tag:9j2D1ibmYEeCxkoX9qozWg==,type:str]
bot_oauth_client_id: K5uU1Y5_tcTj8bNs0g6dWrgxQO-h-JJS
bot_oauth_client_secret: ENC[AES256_GCM,data:ewL1AqPR2nQO7DzCQLrWVpeAB1BIIqRYIfuj+Xhi8YsqO8ZA0+GUS6/BYCzytmZ1qSYuDs2T4qtyagKHycqEhA==,iv:qjtWO0E1qUq1BuRAAhqrHSemiYp/OkD/GTmoYZYzk2M=,tag:ysL1R6RjiYmZ04jgCoDE8w==,type:str]
vekn_username: archon_vekn
vekn_password: ENC[AES256_GCM,data:heUX4yCVbeWXZ1vyT1XF,iv:SjaYzuTgsHEn0/vwa2/W3pi7nhI+x9Aw/0cUv9EYKZw=,tag:KaKkb7hkmu+Y2ZGME8a5dw==,type:str]
twda_github_client_id: Iv23liMqTbrMiNflWqLO
twda_github_installation_id: "143142734"
feedback_github_client_id: Iv23liCZ9rhxGfKpz2mi
feedback_github_installation_id: "142627061"
vapid_private_key: ENC[AES256_GCM,data:Jz+N2qmVREaA+O1uDXe7hw2O/oalh0YJX3UwFxXnDgT8oxIApHE6s4boDQ==,iv:boO8yUXb1O7K2C7sdWtvvWKVbaWI5gmRPg2DgYiRmwA=,tag:9Lqz132hLJxUD/uNG1a0eQ==,type:str]
vapid_public_key: BIofo4Ez7ZW0YNA6qrsCQNIK51j74t2Sb9SAYUJfkVJuXI6WzrsC8evpBg3nl0ezNesFlkPjowjbfzk69aCwzjI
github_oauth_client_id: Ov23liAj1PVLBrQMjDDN
github_oauth_secret: ENC[AES256_GCM,data:Cy2om8srWDnmf9p1ss/j6jWfjz9NKWY+/I6f2mMirhHGn1bGNUH1ow==,iv:5E5eco26id2B4kkTS9kW3HXxVtSbXXpBwDygicXnwBw=,tag:fCO0S9WKCiuaFexlo7ONgQ==,type:str]
remote_backup_access_key: SCW8WD31ZGRMGNCEW52X
remote_backup_secret_key: ENC[AES256_GCM,data:hNbnClZLtU4/z2vgbRGSDApfur4aSU2HblivMPzhUPontHXa,iv:5RGCKiqtMZ04l7PVj92sQZ+mw5sqWR2u/OeI9gOey/w=,tag:zOGG1gDjAZkC5kKJEw142Q==,type:str]
remote_backup_restic_password: ENC[AES256_GCM,data:bnWFGeiFQVVD0urCOCXYbKyHK4TVqQNIUkSxtYU4jJDWuVYpFIwh6UWqPw==,iv:82WgQvx75cEgVR/ERNTj/uLHw/CIw/+ot+kTWGvtjmg=,tag:4wEEWm2xuODNN8R++nKzgQ==,type:str]
db_backup_healthcheck_url: ENC[AES256_GCM,data:Ur/7rzh/PVPHoOIKiaDC+vE55/M4lycL1ytsehNXsf4uXYcnwXG6JmHCCptnJoWkCPRiTz1sLz0=,iv:tu9VZJwK7fGGp/hHkv64+EXsSh+fdpIVjKwA8EmriMI=,tag:lzx0OTkADf2PlJ6uP9NHxA==,type:str]
db_backup_check_healthcheck_url: ENC[AES256_GCM,data:2RCxJ7BzLMrT+zMkFf4k2AzUuU834n0mRByXCCOvXXZVFGKtPAYcPmU3CDhwmtEb0L+4cEDTy70=,iv:D7033X0DH5vqNHqfwfQIgl3rMrTA5UmwrN4+3EoafgA=,tag:ZaX03uOVyhFCYqVoQt03EA==,type:str]
twda_github_fork_installation_id: "155954549"
jwt_private_key: ENC[AES256_GCM,data:2o1UQdEqvMIo/uW1+Ana901XQy5WEta0yxD01+inGPWbGHYnzHhBWYm6Aw==,iv:NJ2+jZwGBuAqerQVpGHahEpNkX7+xRdCTAQjemdGfuM=,tag:mnpQ6hTPvRKkm5cuQRejPA==,type:str]
jwt_public_keys: sC_HVYZCbi0ucwQiLWZNPW1dQQvHsN4v1Zx6dJnyyXg
grafana_cloud_loki_password: ENC[AES256_GCM,data:5U1UmmlN/Kjd5nxle2/lpWxG8Ow85D7Up8y0W8j7pnbWSkBMOf/TG9C/28lvOrm5FZ9Nm+3BPWF4ZzamyrZjqJyGqvAvuYUGuMTAdfoCCOKjCPsnuTxX094a9TFKogHHjeKgEnppsrRAyVz52jQccgfE3/bkk2Qr7F9o2nOByUoGYmzm56sVEb7MP8UBJHcDKhPUjA==,iv:shW7Z2Vr4Cwyz7or/p7bjVprsfjKd1N7AvGw7kVToCw=,tag:rawkg9vVJUuT5CG8/mvOQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGdRTUZwQSBiTkho
            OXUxYlNwU0ZTVGtTVGVoaHJiMTZubDVoN084VVRLYzlyZHQ2V0FvClFpOExTWjNB
            eDluUUZmOHBRY2E1ZHNwTFh6dHN3U21BTU9vanZ5RlgxbTgKLS0tIGVMWEI3eFhk
            MnNBMGtWNGxyZmZ2YnBOYUovTDJnOGlBL3c4SUFNKzE1NWcKYWZpj/Ku69Eod67V
            27UqLEHzF+rP3UQm5ritgUajY4iOxWwJ1RzQYiKB0YxZonpXt28OxTFbO200WakM
            JWUN8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE+Fa+dmnpPBYM0G7xPupl+GkVdF6YFmZ/NkpyqOzWoI
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGUzVldiQSBvMC9F
            S0h1OXg4WWlCR3hMbGtqcmw2ZzN4MDlXZEp3Q1VGamUvY0hhb0c4ClFVM1lvOElp
            cFpwenFkRjg1QTdRVGtkZXY0SHlVUDVrSEdtaExMd2FSM28KLS0tIFduVFJ4UjBF
            R1Q3UkZIcXpOSEc0NkNqak9wbDRVVy9hbUhWTFNYb0VrVlkK7rKFJcBP2F1+Qncu
            lLrPx3ntXUYC5In6YX70FHYKx+Ls+SHdWX0KHeowtnvP8GsFXJl6+9X3drX+mzb0
            KvGPjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHKNdBQ0YRx8ZnlrpkynqRVrNe5zMSLePRAMAu6cgUgC
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IEVINzQ1dyBNdmFM
            RDR3S0EweHgyUmw2bUNBZTNLRU5pMHBoU29ZRkRFVWFleU9hM1ZBCm5wUURLRnRB
            ZktNZ3lSVVlCSzU3MnVuKzV4VTVPTlF6Y091elhGcjFWR0kKLS0tIHMwcFBCYzdU
            ZnE2V0hSZmE2MjhmME10UHpacjJQMmpkazc5UHV2OVVockkK3xXPsc9FPawFy19B
            NHnCuHfqqzFbSFazCNoYqLq0oah8ufvOrkX5EQw7q0FLzuXx9mCfwQePCeLYGNRs
            wtITDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILry5cxe3vALpPMRv8367uwfflP8qOwD5zOwYFzbUwZT
    lastmodified: "2026-09-25T07:54:13Z"
    mac: ENC[AES256_GCM,data:UbbCW2NozYAb/QZsqk7CNAFuWYLLZewh7YYawGZ+XYIbMU24ZXs13/CFFQlZhq6MZf8q4mAkPV3Uall7X1WRjonG1ZIL1Jsa8iH4kMDPT4pu7BCEzF9JTvg4sIMjwpgA/HQIRX0uG60YqsqTdCzR26gn4DyeB3DEkjtH7yhJzDk=,iv:6zwa2IEZpeKxL2KXkRAhafDrMwdq672NtE/0dhB/YtI=,tag:cYsR3KzedsYBSRkK6j6ZoQ==,type:str]
    unencrypted_regex: _(client_id|installation_id|public_keys?|username|access_key)$
    version: 3.13.3
